# Site settings
title: I am Victor Torres
header-img: img/home-bg.jpg
email: vvtorres739@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://iamvictortorres.com"
twitter_username: iamvictortorres
github_username:  crackedlcd

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
